contacts/urls.py
from django.urls import path
from .views import ContactCreateView

app_name = 'contacts'
urlpatterns = [
    path('', ContactCreateView.as_view(), name="contact"),
]

portfolio/urls.py
from django.urls import path
from .views import PortfolioList, PortfolioDetail

app_name = 'portfolio'
urlpatterns = [
    path('', PortfolioList.as_view(), name="portfolios"),
    path('<slug:slug>', PortfolioDetail.as_view(), name="portfolio"),

]

profiles/urls.py
from django.urls import path
from .views import HomePageView

app_name = 'profiles'
urlpatterns = [
    path('', HomePageView.as_view(), name="index"),
]

resume_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Local apps
    path('', include('profiles.urls', namespace='home')),
    path('contact/', include('contacts.urls', namespace='contact')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

certificates/models.py
from django.db import models


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'
        ordering = ["-date"]

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    language = models.CharField(max_length=5, blank=True, null=True)

    def __str__(self):
        return self.name

contacts/models.py
from django.db import models
# from django.urls import reverse


class Contact(models.Model):
    class Meta:
        verbose_name_plural = 'Contacts'
        verbose_name = 'Contact'

    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    text = models.TextField(max_length=1000, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):  # new
    #     return reverse('main:index')

portfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Portfolio(models.Model):
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Portfolio'
        verbose_name_plural = 'Portfolios'

    def __str__(self):
        return self.name

profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'

    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class CustomUser(AbstractUser):
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

contacts/forms.py
from django.forms import ModelForm
# from django.forms import Textarea
from .models import Contact
from django import forms


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email", "text"]

        name = forms.CharField(max_length=100, required=True,
                               widget=forms.TextInput(attrs={
                                   'placeholder': '*Full name..'
                               }))
        email = forms.EmailField(max_length=254, required=True,
                                 widget=forms.TextInput(attrs={
                                     'placeholder': '*Email..'
                                 }))
        text = forms.CharField(max_length=1000, required=True,
                               widget=forms.Textarea(attrs={
                                   'placeholder': '*Message..'
                               }))

certificates/views.py
# from django.shortcuts import render

# Create your views here.

contacts/views.py
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import Contact
from .forms import ContactForm


class ContactCreateView(SuccessMessageMixin, CreateView):
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('home:index')
    success_message = 'Thank you for your message'
    template_name = 'contacts/contact.html'

portfolio/views.py
from django.views.generic import ListView, DetailView
from .models import Portfolio


class PortfolioList(ListView):
    model = Portfolio
    template_name = "portfolio/portfolio.html"


class PortfolioDetail(DetailView):
    model = Portfolio
    template_name = "portfolio/portfolio-detail.html"

profiles/views.py
from django.views.generic import TemplateView
from certificates.models import Certificate
from portfolio.models import Portfolio


class HomePageView(TemplateView):
    template_name = "profiles/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.LANGUAGE_CODE == 'fr':
            certificates = Certificate.objects.filter(is_active=True, language='fr')
        else:
            certificates = Certificate.objects.filter(is_active=True, language='en')
        context["certificates"] = certificates
        portfolio = Portfolio.objects.filter(is_active=True)
        context["portfolio"] = portfolio
        return context

contacts/templates/contacts/contact.html
{% extends 'profiles/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<section>
    <div class="innerPageBannerCol">
        <div class="container">
            <div class="row g-4 g-md-3  align-items-center">
                <div class="col-md-6">
                    <div class="bannerContent">
                        <h1 class="xlTitle pb-md-3">{% trans 'contactHeading' %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="lightBg">
        <div class="container">
            <form id="contactForm" method="post" action={% url "contact:contact" %}>
                {% csrf_token %}
                {{ form.as_p }}
                <input class='btn btnPrimary' type="submit" value="{% trans 'Submit' %}" />
            </form>

        </div>
    </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}

portfolio/templates/portfolio/portfolio-detail.html
{% extends 'profiles/base.html' %}
{% load static %}

{% block content %}
<section>
    <div class="innerPageBannerCol">
        <div class="container">
            <div class="row g-4 g-md-3  align-items-center">
                <div class="col-md-6">
                    <div class="bannerContent">
                        <h1 class="xlTitle pb-md-3">{{object.name}}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="sectionSpaceSm">
        <div class="container">
            {{object.body|safe}}
        </div>
    </div>
</section>
{%endblock%}

portfolio/templates/portfolio/portfolio.html
{% extends 'profiles/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<section>
    <div class="innerPageBannerCol">
        <div class="container">
            <div class="row g-4 g-md-3  align-items-center">
                <div class="col-md-6">
                    <div class="bannerContent">
                        <h1 class="xlTitle pb-md-3">{% trans 'portfolioHeading' %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="lightBg">
        <div class="container">
            <div class="portfolioContentMain">
                <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
                    {% for obj in object_list %}
                    <div class="col-md-6 pColMain">
                        <div class="pCol">
                            <a href="{% url 'portfolio:portfolio' slug=obj.slug %}">
                                <img src="{{obj.image.url}}" alt="..." class="pImg">
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock%}

profiles/templates/profiles/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.png' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/icon.png' %}">
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <title>{% block title %}{% trans 'AppName' %}{%endblock %}</title>

</head>

<body>
    {% include 'profiles/partials/messages.html' %}
    {% include 'profiles/partials/nav.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'profiles/partials/footer.html' %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'js/bootstrap.bundle.min.js' %}">
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

profiles/templates/profiles/index.html
{% extends 'profiles/base.html' %}

{% load static %}
{% load i18n %}

{% include 'main/partials/nav.html' %}

{% block content %}
<section>
    <div class="bannerSection">
        <div class="container">
            <div class="row g-4 g-md-3  align-items-center">
                <div class="col-md-auto order-md-last">
                    <div class="bannerUserImg">
                        <img src="{{me.avatar.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
                    </div>
                </div>
                <div class="col-md">
                    <div class="bannerContent">
                        <h1 class="xlTitle pb-3">{% trans 'HelloHeading' %} {{me.first_name|title}}</h1>
                        <h1></h1>

                        <p>{{me.bio}}</p>
                        <div class="bannerBtnCol">
                            <div class="row">
                                <div class="col-auto">
                                    <a id="cv" download href="{{me.cv.url}}"
                                        class="btn btnPrimary">{% trans 'downloadResume' %}</a>
                                </div>
                                <div class="col-auto">
                                    <a href="{% url 'contact:contact' %}" class="btn btnOutline">Contact</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="sectionSpace pt-0">
        <div class="container">
            <div class="row">
                <div class="col-md-auto">
                    <div class="keySkillCol">
                        <h4 class="smTitle pb-3">{% trans 'keySkills' %}</h4>
                        {% for sk in me.skills.all %}
                        {% if sk.is_key_skill %}
                        <div class="keySkillCard">
                            {% if sk.image %}
                            <div class="ksIconCol">
                                <img src="{{sk.image.url}}" alt="...">
                            </div>
                            {% endif %}
                            <span class="ksText">{{sk.name}}</span>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md">
                    <h4 class="smTitle pb-3">{% trans 'CodingSkills' %}</h4>
                    <div class="progressCol">
                        <div class="progressCard">
                            {% for sk in me.skills.all %}
                            {% if not sk.is_key_skill %}
                            <div class="progressCol">
                                <span class="progressLbl">{{sk.name}}</span>
                                <div class="row g-2 align-items-center">
                                    <div class="col">
                                        <div class="progress progressStyle">
                                            <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%"
                                                aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <span class="pLbl">{{sk.score}}%</span>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="sectionSpaceSm lightBg">
        <div class="container">
            <div class="row pb-3">
                <div class="col">
                    <h4 class="smText regular">{% trans 'certificates' %}</h4>
                </div>
            </div>
            <div class="sliderOuter">
                <div class="swiper certificatesSlider">
                    <div class="swiper-wrapper">
                        {% for c in certificates %}
                        {% if c.is_active %}
                        <div class="swiper-slide">
                            <div class="cardStyle1">
                                <h4 class="mdTitle cs1Title">
                                    <a href="javascript:void(0)">{{c.title}}</a>
                                </h4>
                                <ul class="cardOptionCol">
                                    <li>{{c.date.date}}</li>
                                    <li>{{c.name|title}}</li>
                                </ul>
                                <p>{{c.description}}</p>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}

                    </div>
                </div>
                <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
                <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
                <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="sectionSpace">
        <div class="container">
            <div class="portfolioCol">
                <div class="row pb-3">
                    <div class="col">
                        <h4 class="smText regular">{% trans 'featuredWork' %}</h4>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'portfolio:portfolios' %}" class="simpleLink">{% trans 'viewAll' %}</a>
                    </div>
                </div>
                {% for p in portfolio %}
                {% if p.is_active %}
                <div class="portfolioCard">
                    <div class="row g-4 align-items-center">
                        <div class="col-md-auto">
                            <div class="portfolioImgCol">
                                <a href="{% url 'portfolio:portfolio' slug=p.slug %}"><img src="{{p.image.url}}"
                                        alt="..."></a>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="portfolioContentCol">
                                <h4 class="lgTitle"><a href="{% url 'portfolio:portfolio' slug=p.slug %}">{{p.name}}</a>
                                </h4>
                                <ul class="portfolioOption">
                                    <li><span class="dateLbl">{{p.date.year}}</span></li>
                                </ul>
                                <p>{{p.description}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock content %}

profiles/templates/profiles/partials/footer.html
{% load static %}
{% load i18n %}

<!-- ================================
Start Footer
================================= -->
<footer>
    <div class="footerCol">
        <div class="container">
            <ul class="socialCol">
                <li><a href="https://github.com/nasr-edine"><img src="{% static 'images/github.png' %}" alt="..."></a>
                </li>
                <li><a href="https://www.hackerrank.com/d_nasredine"><img src="{% static 'images/hackerrank.png' %}"
                            alt="..."></a></li>
                <!-- <li><a href="javascript:void(0)"><img src="{% static 'images/twitter.svg' %}" alt="..."></a></li> -->
                <li><a href="https://www.linkedin.com/in/nasr-edine-drai/"><img src="{% static 'images/linkedin.svg' %}"
                            alt="..."></a></li>
            </ul>
            <div class="copyrightCol">
                <p>Copyright ©{% now 'Y' %}{% trans 'copyright' %}<a href="{%url 'contact:contact'%}"
                        target="_blank">Nasr-edine Drai Design</a></p>
            </div>
        </div>
    </div>
</footer>
<!-- ================================
End Footer
================================= -->

profiles/templates/profiles/partials/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags %}
<script>
    alert("{{ message }}")
</script>
{% endif %}
{% endfor %}
{% endif %}

profiles/templates/profiles/partials/nav.html
{% load static %}
{% load i18n %}

<header>
    <div class="headerCol">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-auto">
                    <div class="logoCol"><a href="{%url 'home:index'%}"><img src="{% static 'images/icon.png' %}"
                                alt="..."></a></div>
                </div>
                <div class="col">
                    <div class="d-md-none">
                        <button class="navToggle">
                            <span class="navToggle__text">Toggle Menu</span>
                        </button>
                    </div>
                    <div class="navCollapseCol">
                        <div class="navCol">
                            <ul>
                                <li><a href="{%url 'home:index'%}">{% trans 'HomePage' %}</a></li>
                                <li><a href="{%url 'portfolio:portfolios' %}">Portfolio</a></li>
                                <li><a href="{%url 'contact:contact'%}">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>